// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPfsyUHTeidDHgAuw9Ac3CTFwLnQM97Zc',
    appId: '1:733985631902:web:fbb95fd9529e439c4e958f',
    messagingSenderId: '733985631902',
    projectId: 'lozido-d7efc',
    authDomain: 'lozido-d7efc.firebaseapp.com',
    storageBucket: 'lozido-d7efc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgCZsfNF4m2toI_Yof2LuXSnmCuj5zLmI',
    appId: '1:733985631902:android:cbd75ecf3f3e429a4e958f',
    messagingSenderId: '733985631902',
    projectId: 'lozido-d7efc',
    storageBucket: 'lozido-d7efc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-rlpg3wIsrut4UIA69msiGAJISDD-caQ',
    appId: '1:733985631902:ios:21bff97392fb9da74e958f',
    messagingSenderId: '733985631902',
    projectId: 'lozido-d7efc',
    storageBucket: 'lozido-d7efc.firebasestorage.app',
    iosBundleId: 'com.example.lozidoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-rlpg3wIsrut4UIA69msiGAJISDD-caQ',
    appId: '1:733985631902:ios:21bff97392fb9da74e958f',
    messagingSenderId: '733985631902',
    projectId: 'lozido-d7efc',
    storageBucket: 'lozido-d7efc.firebasestorage.app',
    iosBundleId: 'com.example.lozidoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPfsyUHTeidDHgAuw9Ac3CTFwLnQM97Zc',
    appId: '1:733985631902:web:0aa0583b23111da94e958f',
    messagingSenderId: '733985631902',
    projectId: 'lozido-d7efc',
    authDomain: 'lozido-d7efc.firebaseapp.com',
    storageBucket: 'lozido-d7efc.firebasestorage.app',
  );
}
